version: '3.8'

services:
  database:
    image: postgres:12.0
    environment:
      - POSTGRES_DB=judge
      - POSTGRES_USER=judge
      - POSTGRES_PASSWORD=uhdtas
    volumes:
      - pgdb:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    build:
      context: ../..
      dockerfile: docker/dev/dockerfile
    command: bash -c docker/dev/command.sh
    # command: >
    #   bash -c "npm start &
    #            /opt/environ/bin/python3 manage.py migrate &&
    #            /opt/environ/bin/python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../..:/code
      - varwww:/var/www/judge
      - problems:/problems
    ports:
      - '8000:8000'
    depends_on:
      - database
  grader:
    build:
      context: ../..
      dockerfile: docker/dev/dockerfile.grader
    command: bash -c "bash grader-firewall.sh && /code/environ/bin/python3 manage.py grader"
    volumes:
      - problems:/problems
    cap_add:
      - NET_ADMIN

volumes:
  pgdb:
  problems:
  varwww:
