image: python:2.7

services:
  - postgres:9.5.0

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - apt-get update 1>/dev/null 2>/dev/null
  - apt-get install python-pip --assume-yes 1>/dev/null 2>/dev/null
  - pip install -r requirements.txt 1>/dev/null 2>/dev/null
  - bash generate_test_settings.sh

all_tests:
  script:
   - python manage.py test
