image: python:3.7

services:
  - postgres:9.5.0

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - apt-get update
  - apt-get install python-pip --assume-yes
  - pip install -r requirements.txt
  - bash generate_test_settings.sh

all_tests:
  script:
   - python manage.py test
