#!/bin/sh

settings=$(cat <<-END
[debugging]
DEBUG: false
DEBUG_TOOLBAR: false

[database]
DATABASE_NAME: default
DATABASE_USER: postgres
DATABASE_PASS: postgres
DATABASE_HOST: postgres
DATABASE_PORT: 5432

[secrets]
SECRET_KEY: dhs7bvc2r*li%9jjf6^e25#y9du-rcj_5+=t9arf308p4)zpu!

[email]
EMAIL_USE_TLS: true
EMAIL_HOST: -
EMAIL_PORT: 587
EMAIL_HOST_USER: -
EMAIL_HOST_PASSWORD: -
DEFAULT_FROM_EMAIL: -
EMAIL_TIMEOUT: 20

[others]
STATIC_ROOT: /var/www/judge/static
MEDIA_ROOT: /var/www/judge/media

[grader]
RESOURCES_FOLDER: -
SANDBOX_FOLDER: -
PROBLEMS_FOLDER: -

[cache]
BACKEND: django.core.cache.backends.locmem.LocMemCache
LOCATION: mog-cache

[social]
SOCIAL_AUTH_FACEBOOK_KEY:-
SOCIAL_AUTH_FACEBOOK_SECRET:-
SOCIAL_AUTH_FACEBOOK_SCOPE:-
SOCIAL_AUTH_GITHUB_KEY:-
SOCIAL_AUTH_GITHUB_SECRET:-
SOCIAL_AUTH_GITHUB_SCOPE:-
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS_LOCALE:-
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS_FIELDS:-
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY:-
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET:-
SOCIAL_AUTH_GOOGLE_SCOPE:-

[palantir]
LOG_REQUESTS: false
END
)

if [ ! -f "settings.ini" ]
then
    echo "${settings}" > "settings.ini"
fi
