from django.urls import re_path

from . import views

app_name = "mog"
urlpatterns = [
    re_path(r"^health/$", views.health, name="health"),
    re_path(r"^faq/$", views.faq, name="faq"),
    re_path(r"^privacy/$", views.privacy, name="privacy"),
    re_path(r"^feedback$", views.feedback_list, name="feedback_list"),
    re_path(
        r"^feedback/(?P<feedback_id>[0-9]+)$",
        views.FeedbackView.as_view(),
        name="feedback_view",
    ),
    re_path(r"^feedback/create/$", views.feedback_create, name="feedback_create"),
    re_path(
        r"^api/institution/list/$", views.institution_list, name="api_institution_list"
    ),
    re_path(
        r"^api/instance/group/list/$",
        views.instance_group_list,
        name="api_instance_group_list",
    ),
    re_path(
        r"^api/instance/(?P<instance_pk>[0-9]+)/edit/group/$",
        views.instance_edit_group,
        name="api_instance_edit_group",
    ),
    re_path(
        r"^api/instance/(?P<instance_pk>[0-9]+)/edit/render_description/$",
        views.instance_edit_render_description,
        name="api_instance_edit_render_description",
    ),
    re_path(
        r"^api/instance/(?P<instance_pk>[0-9]+)/edit/team/$",
        views.instance_edit_team,
        name="api_instance_edit_team",
    ),
    re_path(
        r"^api/instance/(?P<instance_pk>[0-9]+)/edit/user/$",
        views.instance_edit_user,
        name="api_instance_edit_user",
    ),
    re_path(
        r"^api/instance/(?P<instance_pk>[0-9]+)/edit/enable/$",
        views.instance_edit_enable,
        name="api_instance_edit_enable",
    ),
    re_path(
        r"^api/contest/permission/(?P<permission_pk>[0-9]+)/edit/granted$",
        views.contest_permission_edit_granted,
        name="api_contest_permission_edit_granted",
    ),
    re_path(
        r"^message/send/(?P<user_id>[0-9]+)$", views.send_message, name="send_message"
    ),
    re_path(r"^teams/json$", views.teams_json, name="teams_json"),
    re_path(r"^team/create$", views.create_team, name="create_team"),
    re_path(
        r"^team/remove/(?P<team_id>[0-9]+)$", views.remove_team, name="remove_team"
    ),
    re_path(r"^team/edit/(?P<team_id>[0-9]+)$", views.edit_team, name="edit_team"),
    re_path(
        r"^comment/(?P<comment_id>[0-9]+)/edit/$",
        views.edit_comment,
        name="comment_edit",
    ),
    re_path(
        r"^comment/(?P<comment_id>[0-9]+)/remove/$",
        views.remove_comment,
        name="comment_remove",
    ),
    re_path(r"^posts/$", views.PostListView.as_view(), name="posts"),
    re_path(
        r"^post/edit/(?P<post_id>[0-9]+)$",
        views.EditPostView.as_view(),
        name="post_edit",
    ),
    re_path(r"^post/create$", views.PostCreateView.as_view(), name="post_create"),
    re_path(
        r"^post/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$",
        views.PostDetailView.as_view(),
        name="post",
    ),
    re_path(r"^checkers/$", views.view_checker, name="view_checker"),
    re_path(
        r"^checkers/create/$", views.CreateCheckerView.as_view(), name="create_checker"
    ),
    re_path(
        r"^problem/test/(?P<problem_id>[0-9]+)/view$", views.view_test, name="view_test"
    ),
    re_path(
        r"^problem/test/(?P<problem_id>[0-9]+)/remove$",
        views.remove_test,
        name="remove_test",
    ),
    re_path(
        r"^problem/test/(?P<problem_id>[0-9]+)/list$",
        views.ProblemTestsView.as_view(),
        name="problem_tests",
    ),
    re_path(
        r"^problem/checker/(?P<problem_id>[0-9]+)/view$",
        views.ProblemCheckerView.as_view(),
        name="problem_checker",
    ),
    re_path(
        r"^problem/checker/(?P<problem_id>[0-9]+)/create$",
        views.CheckerView.as_view(),
        name="checker",
    ),
    re_path(
        r"^problem/remove/(?P<problem_id>[0-9]+)$",
        views.remove_problem,
        name="problem_remove",
    ),
    re_path(
        r"^problem/edit/(?P<problem_id>[0-9]+)$",
        views.ProblemEditView.as_view(),
        name="problem_edit",
    ),
    re_path(
        r"^problem/(?P<problem_id>[0-9]+)/(?P<slug>[-\w]+)/$",
        views.problem,
        name="problem",
    ),
    re_path(r"^problems/$", views.ProblemListView.as_view(), name="problems"),
    re_path(
        r"^clarification/create/$",
        views.clarification_create,
        name="clarification_create",
    ),
    re_path(
        r"^clarification/(?P<clarification_id>[0-9]+)/edit/$",
        views.clarification_edit,
        name="clarification_edit",
    ),
    re_path(
        r"^contest/register/(?P<contest_id>[0-9]+)$",
        views.contest_register,
        name="contest_register",
    ),
    re_path(
        r"^contest/register/user/(?P<contest_id>[0-9]+)$",
        views.contest_register_user,
        name="contest_register_user",
    ),
    re_path(
        r"^contest/register/team/(?P<contest_id>[0-9]+)$",
        views.contest_register_team,
        name="contest_register_team",
    ),
    re_path(
        r"^contest/remove/instance/(?P<instance_id>[0-9]+)$",
        views.contest_remove_instance,
        name="contest_remove_instance",
    ),
    re_path(
        r"^contest/remove/registration/(?P<contest_id>[0-9]+)$",
        views.contest_remove_registration,
        name="contest_remove_registration",
    ),
    re_path(
        r"^contest/instances/info/(?P<contest_id>[0-9]+)$",
        views.contest_instances_info,
        name="contest_instances_info",
    ),
    re_path(
        r"contest/(?P<contest_id>[0-9]+)/registration/multiple/register/user/$",
        views.contest_registration_multiple_register_user,
        name="contest_registration_multiple_register_user",
    ),
    re_path(
        r"contest/(?P<contest_id>[0-9]+)/registration/multiple/register/team/$",
        views.contest_registration_multiple_register_team,
        name="contest_registration_multiple_register_team",
    ),
    re_path(
        r"contest/(?P<contest_id>[0-9]+)/registration/multiple/unregister/$",
        views.contest_registration_multiple_unregister,
        name="contest_registration_multiple_unregister",
    ),
    re_path(
        r"contest/(?P<contest_id>[0-9]+)/registration/multiple/edit-group/$",
        views.contest_registration_multiple_edit_group,
        name="contest_registration_multiple_edit_group",
    ),
    re_path(
        r"contest/(?P<contest_id>[0-9]+)/registration/multiple/enable/$",
        views.contest_registration_multiple_enable,
        name="contest_registration_multiple_enable",
    ),
    re_path(
        r"contest/(?P<contest_id>[0-9]+)/registration/multiple/disable/$",
        views.contest_registration_multiple_disable,
        name="contest_registration_multiple_disable",
    ),
    re_path(
        r"^contest/(?P<contest_id>[0-9]+)/clarifications$",
        views.contest_clarifications,
        name="contest_clarifications",
    ),
    re_path(
        r"^contest/(?P<contest_id>[0-9]+)/create_problem$",
        views.CreateProblemInContestView.as_view(),
        name="contest_create_problem",
    ),
    re_path(
        r"^contest/overview/(?P<contest_id>[0-9]+)$",
        views.contest_overview,
        name="contest_overview",
    ),
    re_path(
        r"^contest/problems/(?P<contest_id>[0-9]+)$",
        views.contest_problems,
        name="contest_problems",
    ),
    re_path(
        r"^contest/saris/(?P<contest_id>[0-9]+)$",
        views.contest_saris,
        name="contest_saris",
    ),
    re_path(
        r"^contest/saris/(?P<contest_id>[0-9]+)/download$",
        views.download_json_saris,
        name="download_json_saris",
    ),
    re_path(
        r"^contest/standing/(?P<contest_id>[0-9]+)$",
        views.contest_standing,
        name="contest_standing",
    ),
    re_path(
        r"^contest/submissions/(?P<contest_id>[0-9]+)$",
        views.contest_submissions,
        name="contest_submissions",
    ),
    re_path(
        r"^contest/submissions/export/(?P<contest_id>[0-9]+)$",
        views.contest_submissions_export,
        name="contest_submissions_export",
    ),
    re_path(
        r"^contest/registration/(?P<contest_id>[0-9]+)$",
        views.contest_registration,
        name="contest_registration",
    ),
    re_path(
        r"^contest/edit/(?P<contest_id>[0-9]+)$",
        views.ContestEditView.as_view(),
        name="contest_edit",
    ),
    re_path(
        r"^contest/remove/(?P<contest_id>[0-9]+)$",
        views.remove_contest,
        name="contest_remove",
    ),
    re_path(
        r"^contest/(?P<contest_id>[0-9]+)/team/(?P<team_id>[0-9]+)/submissions$",
        views.team_submissions,
        name="team_submissions",
    ),
    re_path(
        r"^contest/create$", views.ContestCreateView.as_view(), name="contest_create"
    ),
    re_path(r"^contests/$", views.contests, name="contests"),
    re_path(
        r"^contest/manage/(?P<contest_id>[0-9]+)$",
        views.contest_manage,
        name="contest_manage",
    ),
    re_path(
        r"^contest/manage/import/baylor/(?P<contest_id>[0-9]+)$",
        views.contest_manage_import_baylor,
        name="contest_manage_import_baylor",
    ),
    re_path(
        r"^contest/manage/import/guest/(?P<contest_id>[0-9]+)$",
        views.contest_manage_import_guest,
        name="contest_manage_import_guest",
    ),
    re_path(
        r"^contest/manage/export/password/(?P<contest_id>[0-9]+)$",
        views.contest_manage_export_password,
        name="contest_manage_export_password",
    ),
    re_path(
        r"^contest/permission/(?P<contest_id>[0-9]+)$",
        views.contest_permission,
        name="contest_permission",
    ),
    re_path(
        r"^contest/permission/assign/(?P<contest_id>[0-9]+)$",
        views.contest_add_permission,
        name="contest_add_permission",
    ),
    re_path(
        r"^contest/permission/import/(?P<contest_id>[0-9]+)$",
        views.contest_permission_import,
        name="contest_permission_import",
    ),
    re_path(
        r"^contest/permission/export/(?P<contest_id>[0-9]+)$",
        views.contest_permission_export,
        name="contest_permission_export",
    ),
    re_path(
        r"^contest/rate/(?P<contest_id>[0-9]+)$",
        views.rate_contest,
        name="rate_contest",
    ),
    re_path(
        r"^contest/unrate/(?P<contest_id>[0-9]+)$",
        views.unrate_contest,
        name="unrate_contest",
    ),
    re_path(
        r"^contest/(?P<contest_id>[0-9]+)/unfreeze/$",
        views.unfreeze_contest,
        name="contest_unfreeze",
    ),
    re_path(
        r"^contest/stats/(?P<contest_id>[0-9]+)$",
        views.contest_stats,
        name="contest_stats",
    ),
    re_path(
        r"^contest/ratings/(?P<contest_id>[0-9]+)$",
        views.contest_rating_changes,
        name="contest_ratings",
    ),
    re_path(
        r"^contest/csv/(?P<contest_id>[0-9]+)$", views.contest_csv, name="contest_csv"
    ),
    re_path(
        r"^contest/export/baylor/(?P<contest_id>[0-9]+)$",
        views.contest_baylor,
        name="contest_baylor",
    ),
    re_path(
        r"^submission/(?P<submission_id>[0-9]+)/$", views.submission, name="submission"
    ),
    re_path(
        r"^submission/rejudge/(?P<submission_id>[0-9]+)/$",
        views.rejudge,
        name="submission_rejudge",
    ),
    re_path(r"^submissions/$", views.submissions, name="submissions"),
    re_path(r"^users/json$", views.users_json, name="users_json"),
    re_path(r"^users/$", views.UserListView.as_view(), name="users"),
    re_path(r"^user/(?P<user_id>[0-9]+)/$", views.user_profile, name="user"),
    re_path(
        r"^user/edit/(?P<user_id>[0-9]+)/$",
        views.UserEditView.as_view(),
        name="user_edit",
    ),
    re_path(
        r"^user/messages/(?P<user_id>[0-9]+)/$",
        views.user_messages,
        name="user_messages",
    ),
    re_path(r"^user/teams/(?P<user_id>[0-9]+)/$", views.user_teams, name="user_teams"),
    re_path(r"^submit/(?P<problem_id>[0-9]+)/$", views.Submit.as_view(), name="submit"),
    re_path(r"^$", views.index, name="index"),
]
