# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161017_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatar', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='compiler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Compiler', verbose_name='Compiler'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_tags',
            field=models.BooleanField(default=True, verbose_name='Show tags'),
        ),
    ]
