# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170426_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('browser', 'Code Browser')], max_length=10, null=True),
        ),
    ]
