# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='compilers',
            field=models.ManyToManyField(to='api.Compiler'),
        ),
    ]
