# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_problem_compilers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
