# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_auto_20170504_2300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestinstance",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="api.Team",
            ),
        ),
        migrations.AlterField(
            model_name="contestinstance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
