# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161025_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
