# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_auto_20170506_1250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestinstance",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
