# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170506_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
