# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_problem_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
