# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-28 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_userprofile_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
