# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 19:05
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_checker_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.UUIDImageName("user/avatar"),
                verbose_name="Avatar",
            ),
        ),
    ]
