# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171103_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Country Name')),
                ('flag', models.CharField(max_length=128, verbose_name='Country Flag URL')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.RemoveField(
            model_name='institution',
            name='country',
        ),
    ]
