# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_auto_20171103_2314"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="country",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Country"
            ),
        ),
    ]
