# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_institution_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
