# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171103_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('hopscotch', 'hopscotch'), ('ttcn', 'ttcn'), ('ambiance-mobile', 'ambiance-mobile'), ('paraiso-light', 'paraiso-light'), ('icecoder', 'icecoder'), ('zenburn', 'zenburn'), ('erlang-dark', 'erlang-dark'), ('seti', 'seti'), ('midnight', 'midnight'), ('tomorrow-night-bright', 'tomorrow-night-bright'), ('panda-syntax', 'panda-syntax'), ('bespin', 'bespin'), ('ambiance', 'ambiance'), ('neo', 'neo'), ('solarized', 'solarized'), ('base16-light', 'base16-light'), ('vibrant-ink', 'vibrant-ink'), ('abcdef', 'abcdef'), ('yeti', 'yeti'), ('mbo', 'mbo'), ('xq-light', 'xq-light'), ('twilight', 'twilight'), ('rubyblue', 'rubyblue'), ('base16-dark', 'base16-dark'), ('neat', 'neat'), ('dracula', 'dracula'), ('cobalt', 'cobalt'), ('lesser-dark', 'lesser-dark'), ('3024-night', '3024-night'), ('pastel-on-dark', 'pastel-on-dark'), ('liquibyte', 'liquibyte'), ('colorforth', 'colorforth'), ('blackboard', 'blackboard'), ('monokai', 'monokai'), ('xq-dark', 'xq-dark'), ('elegant', 'elegant'), ('3024-day', '3024-day'), ('night', 'night'), ('mdn-like', 'mdn-like'), ('tomorrow-night-eighties', 'tomorrow-night-eighties'), ('isotope', 'isotope'), ('material', 'material'), ('eclipse', 'eclipse'), ('paraiso-dark', 'paraiso-dark'), ('railscasts', 'railscasts'), ('the-matrix', 'the-matrix')], max_length=25, null=True, verbose_name='Code Editor Theme'),
        ),
    ]
