# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-12 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_auto_20171103_2354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="balloon",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Balloon color"
            ),
        ),
    ]
