# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-12 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171112_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='letter_color',
            field=models.CharField(choices=[('#ffffff', 'white'), ('#000000', 'black')], default='#ffffff', max_length=20),
        ),
    ]
