# Generated by Django 2.0 on 2017-12-31 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_problem_letter_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Checker'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.ContestInstance'),
        ),
        migrations.AlterField(
            model_name='team',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Institution'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='compiler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Compiler', verbose_name='Compiler'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Institution', verbose_name='Institution'),
        ),
    ]
