# Generated by Django 2.0 on 2018-03-07 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0020_userprofile_email_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clarification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("question", models.CharField(max_length=2048)),
                ("answer", models.TextField(blank=True, null=True)),
                ("asked_date", models.DateTimeField(auto_now_add=True)),
                ("answered_date", models.DateTimeField(null=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clarifications",
                        to="api.Contest",
                    ),
                ),
                (
                    "fixer",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who clarify",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clarifications",
                        to="api.Problem",
                    ),
                ),
                (
                    "seen",
                    models.ManyToManyField(
                        related_name="seen_clarifications", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clarifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who ask for clarification",
                    ),
                ),
            ],
        ),
    ]
