# Generated by Django 2.0 on 2018-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_contestinstance_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("normal", "normal"),
                    ("frozen", "frozen"),
                    ("death", "death"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
    ]
