# Generated by Django 2.0 on 2018-04-07 13:14
import os

from django.db import migrations
from django.conf import settings


def sql_migrations():
    folder = os.path.join(os.path.join(settings.BASE_DIR, "db_scripts"))
    for name in sorted(os.listdir(folder)):
        with open(os.path.join(folder, name), "r") as file:
            sql = "".join(file.readlines()).replace(
                "${USERNAME}", settings.DEFAULT_DATABASE["USER"]
            )
            yield migrations.RunSQL(sql)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_auto_20180407_0912"),
    ]

    operations = list(sql_migrations())
