# Generated by Django 2.0 on 2018-09-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_contest_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
