# Generated by Django 2.0 on 2019-09-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_contest_needs_unfreeze"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administrator"),
                    ("browser", "Code Browser"),
                    ("observer", "Observer"),
                    ("judge", "Judge"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
