# Generated by Django 2.0 on 2019-09-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_contestpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="samples",
            field=models.TextField(
                blank=True, null=True, verbose_name="Sample inputs/outputs"
            ),
        ),
    ]
