# Generated by Django 2.0 on 2019-09-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_problem_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='multiple_limits',
            field=models.TextField(blank=True, verbose_name='JSON with memory & time limit per compiler'),
        ),
    ]
