# Generated by Django 2.0 on 2019-10-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_problem_multiple_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingchange',
            name='seed',
            field=models.FloatField(default=0),
        ),
    ]
