# Generated by Django 2.0 on 2022-09-11 18:54

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Problem = apps.get_model("api", "Problem")

    Problem.objects.all().update(is_html=True)
    # TODO: update Django, improves performance (something like below Django >= 2.2)
    # problems = Problem.objects.all().update(is_html=True)
    # for problem in problems:
    #     problem.is_html = True
    # Problem.objects.bulk_update(problems, ["is_html"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_ratingchange_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="is_html",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
