# Generated by Django 2.0 on 2023-02-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_ratingchange_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestinstance",
            name="is_active",
            field=models.BooleanField(
                default=True,
                verbose_name="If true, it will allows the instance to submit to the corresponding contest.",
            ),
        ),
    ]
