# Generated by Django 2.0 on 2023-02-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_contestinstance_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="is_html",
            field=models.BooleanField(
                default=True,
                verbose_name="If true, the problem source is written in Text Rich Editor, else with Simple Markdown Editor.",
            ),
        ),
    ]
