# Generated by Django 2.0 on 2023-05-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_problem_is_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'CREATED'), ('viewed', 'VIEWED'), ('closed', 'CLOSED')], max_length=20, null=True),
        ),
    ]
