# Generated by Django 2.0 on 2023-05-28 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0042_userfeedback_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedback",
            name="assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "OPEN"),
                    ("in_progress", "IN_PROGRESS"),
                    ("closed", "CLOSED"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
