# Generated by Django 2.0 on 2024-09-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_compiler_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='backend',
            field=models.CharField(choices=[('testlib.h (0.9.10-SNAPSHOT)', 'testlib.h'), ('testlib.h (0.9.42-SNAPSHOT)', 'testlib-0.9.42-SNAPSHOT.h'), ('testlib4j.jar', 'testlib4j.jar')], default='testlib.h', max_length=32),
        ),
    ]
