# Generated by Django 2.0 on 2024-12-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0046_auto_20240929_1518"),
    ]

    operations = [
        migrations.AddField(
            model_name="compiler",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
