# Generated by Django 2.0 on 2025-09-23 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_compiler_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="compiler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Compiler",
                verbose_name="Compiler",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Institution",
                verbose_name="Institution",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hopscotch", "hopscotch"),
                    ("ttcn", "ttcn"),
                    ("ambiance-mobile", "ambiance-mobile"),
                    ("paraiso-light", "paraiso-light"),
                    ("icecoder", "icecoder"),
                    ("zenburn", "zenburn"),
                    ("erlang-dark", "erlang-dark"),
                    ("seti", "seti"),
                    ("midnight", "midnight"),
                    ("tomorrow-night-bright", "tomorrow-night-bright"),
                    ("panda-syntax", "panda-syntax"),
                    ("bespin", "bespin"),
                    ("ambiance", "ambiance"),
                    ("neo", "neo"),
                    ("solarized", "solarized"),
                    ("base16-light", "base16-light"),
                    ("vibrant-ink", "vibrant-ink"),
                    ("abcdef", "abcdef"),
                    ("yeti", "yeti"),
                    ("mbo", "mbo"),
                    ("xq-light", "xq-light"),
                    ("twilight", "twilight"),
                    ("rubyblue", "rubyblue"),
                    ("base16-dark", "base16-dark"),
                    ("neat", "neat"),
                    ("dracula", "dracula"),
                    ("cobalt", "cobalt"),
                    ("lesser-dark", "lesser-dark"),
                    ("3024-night", "3024-night"),
                    ("pastel-on-dark", "pastel-on-dark"),
                    ("liquibyte", "liquibyte"),
                    ("colorforth", "colorforth"),
                    ("blackboard", "blackboard"),
                    ("monokai", "monokai"),
                    ("xq-dark", "xq-dark"),
                    ("elegant", "elegant"),
                    ("3024-day", "3024-day"),
                    ("night", "night"),
                    ("mdn-like", "mdn-like"),
                    ("tomorrow-night-eighties", "tomorrow-night-eighties"),
                    ("isotope", "isotope"),
                    ("material", "material"),
                    ("eclipse", "eclipse"),
                    ("paraiso-dark", "paraiso-dark"),
                    ("railscasts", "railscasts"),
                    ("the-matrix", "the-matrix"),
                ],
                max_length=25,
                null=True,
                verbose_name="Code Editor Theme",
            ),
        ),
    ]
