version: "3.8"

services:
  database:
    image: postgres:11.5
    environment:
      - POSTGRES_DB=judge
      - POSTGRES_USER=judge
      - POSTGRES_PASSWORD=uhdtas
    volumes:
      - pgdb:/var/lib/postgresql/data
  api:
    build:
      context: ../..
      dockerfile: docker/prod/dockerfile
    command: environ/bin/gunicorn --workers 4 -b :8000 judge.wsgi:application
    volumes:
      - varwww:/var/www/judge
      - problems:/problems
    ports:
      - "8000:8000"
    depends_on:
      - database
  grader:
    build:
      context: ../..
      dockerfile: docker/prod/dockerfile.grader
    command: bash -c "bash grader-firewall.sh && /code/environ/bin/python3 manage.py grader"
    volumes:
      - problems:/problems
    cap_add:
      - NET_ADMIN
  ######################################################################
  # Monitoring
  ######################################################################
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./web-config.yml:/etc/prometheus/web-config.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web-config.yml"
      - "--web.external-url=/prometheus/"
      - "--web.route-prefix=/prometheus/"
    ports:
      - "9090:9090"
    restart: unless-stopped

volumes:
  pgdb:
  problems:
  varwww:
