version: '3.8'

services:
  database:
    image: postgres:12.0
    environment:
      - POSTGRES_DB=judge
      - POSTGRES_USER=judge
      - POSTGRES_PASSWORD=uhdtas
    volumes:
      - pgdb:/var/lib/postgresql/data
  api:
    build:
      context: ../..
      dockerfile: docker/prod/dockerfile
    command: environ/bin/gunicorn --workers 4 -b :8000 judge.wsgi:application
    volumes:
      - varwww:/var/www/judge
      - problems:/problems
    ports:
      - '8000:8000'
    depends_on:
      - database
  grader:
    build:
      context: ../..
      dockerfile: docker/prod/dockerfile.grader
    command: bash -c "bash grader-firewall.sh && /code/environ/bin/python3 manage.py grader"
    volumes:
      - problems:/problems
    cap_add:
      - NET_ADMIN

volumes:
  pgdb:
  problems:
  varwww:
