version: '3.8'

services:
  database:
    image: postgres:11.5
    environment:
      - POSTGRES_DB=judge
      - POSTGRES_USER=judge
      - POSTGRES_PASSWORD=uhdtas
    volumes:
      - pg-database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    build:
      context: ../..
      dockerfile: docker/prod/dockerfile
    command: environ/bin/gunicorn --workers 4 -b :8000 judge.wsgi:application
    volumes:
      - django-media:/var/www/judge/media
      - judge-problems:/problems
    ports:
      - '8000:8000'
    depends_on:
      - database
  grader:
    build:
      context: ../..
      dockerfile: docker/prod/dockerfile.grader
    command: bash -c "bash grader-firewall.sh && /code/environ/bin/python3 manage.py grader"
    volumes:
      - judge-problems:/problems
    cap_add:
      - NET_ADMIN

volumes:
  django-media:
  pg-database:
  judge-problems:
